docs/conf.py, docs/index.rst, docs/python-api, requirements.txt, scripts/python-skywater-pdk/LICENSE, scripts/python-skywater-pdk/README.rst, scripts/python-skywater-pdk/docs/index.rst, scripts/python-skywater-pdk/docs/skywater_pdk.rst, scripts/python-skywater-pdk/setup.py, scripts/python-skywater-pdk/skywater_pdk/__init__.py, scripts/python-skywater-pdk/skywater_pdk/base.py, scripts/python-skywater-pdk/skywater_pdk/sizes.py, scripts/python-skywater-pdk/skywater_pdk/utils.py
Initial version of the [`python-skywater-pdk`](https://github.com/google/skywater-pdk/tree/master/scripts/python-skywater-pdk) module which provides a programmatic API working with the [`skywater-pdk`](https://github.com/google/skywater-pdk) module and it's content.
Currently the API provides;
- A way to extract the version, library and cell name from a given path.
- A way to extract the cell size from the file and module name.
In the future it will provide;
- A way to get cell metadata.
- A way to understand files and their sources.
- A way to decode corner information in file names.
- Tools for generating output based on various inputs.
=> Initial version of python-skywater-pdk module

.github/autolabeler.yml
See https://github.com/google/skywater-pdk/issues/36.
Currently uses the [Probot Autolabeler](https://github.com/apps/probot-autolabeler) as I have used that before. It should probably be converted to use one of the GitHub actions in the future.
=> infra: Adding autolabeler configuration.

scripts/python-skywater-pdk/skywater_pdk/base.py
[flake8](http://flake8.pycqa.org) testing of https://github.com/google/skywater-pdk on Python 3.8.3
$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./scripts/python-skywater-pdk/skywater_pdk/base.py:332:71: F821 undefined name 'minor'
return (self.milestone, self.major, self.minor, self.commits, minor)
^
1     F821 undefined name 'minor'
1
```
https://flake8.pycqa.org/en/latest/user/error-codes.html
On the flake8 test selection, this PR does _not_ focus on "_style violations_" (the majority of flake8 error codes that [__psf/black__](https://github.com/psf/black) can autocorrect).  Instead these tests are focus on runtime safety and correctness:
* E9 tests are about Python syntax errors usually raised because flake8 can not build an Abstract Syntax Tree (AST). …
=> Undefined name: minor -> self.hash

.github/labels.yml
* Add `help-wanted` and `good-first-issue` labels.
* Document the general label color scheme.
* Pull the non-color grouped labels to the top of the file.
=> infra: Improve the labels a little.

.gitignore, Makefile, scripts/python-skywater-pdk/docs/skywater_pdk.rst, scripts/python-skywater-pdk/skywater_pdk/corners.py, scripts/python-skywater-pdk/skywater_pdk/liberty.py, scripts/python-skywater-pdk/skywater_pdk/sizes.py, scripts/python-skywater-pdk/skywater_pdk/utils.py
By typing `make timing` liberty files will be generated from the timing data found in the json files.
Fixes https://github.com/google/skywater-pdk/issues/6 and https://github.com/google/skywater-pdk/issues/8
=> Adding liberty file generation

.travis.yml, Makefile, requirements.txt
Fixes #45
If `make lint-python` is not run before `make env` then it fails to complete in 10 minutes which times out Travis CI.
=> Makefile: Add a make lint-python command

Makefile
If a library directory doesn't contain a 'cells' subdir, it's most
likely not checked out, so skip it
Fixes #76
Signed-off-by: Sylvain Munaut <tnt@246tNt.com>
=> build: Don't try to make timing for non-checked out submodules

scripts/python-skywater-pdk/skywater_pdk/liberty.py
The liberty file output generator now respects the type information found in the `define` statements.
Fixes https://github.com/google/skywater-pdk/issues/72, https://github.com/google/skywater-pdk/issues/70 and https://github.com/google/skywater-pdk/issues/69.
=> Fix a number of issues with the generated liberty output

docs/conf.py, docs/requirements.txt
* Install sphinx-verilog-domain.
* Update for the sphinxcontrib-verilog-diagrams name change.
* Use the SymbiFlow version of Symbolator.
=> docs: Fixing requirements.txt

docs/rules/rcx.rst
The values should probably be described just as "approximations".
I didn't open an issue as this is a very small change.
=> Fix typo: "an approximations"

environment.yml
Python 3.9 has been released but a lot of packages have not yet moved
forward.
=> env: Lock to Python 3.8

docs/contents/libraries/foundry-provided.rst
* Changed `Sky30` to `SKY130`
* Changed `S130` to `SKY130`
* Removed a dangling reference to a table
* Clarified size comparison of hvl library
=> Corrected minor typos

.gitmodules
* Fixes all the version directories pointing at `v0.20.1` revision `d717cd4`.
* Fixes missing `v` in the directory names (which was inconsistent with other libraries).
* Updates the primitive submodule to fix names of nwell and rdl generic resistors (Fixes #168).
=> Updates to the primitive libraries.

docs/rules/periphery-rules.rst, docs/rules/periphery/periphery-split-csv.py
Fixes periphery-rules generation script and resulting rst by;
* Handles '\n' in CSV rules description strings.
* Multi-line descriptions and bullet lists are handled separately.
* Single item bullet lists without header are reduced to text.
Fixes #71
=> Periphery csv description line break handling

docs/rules/periphery-rules.rst, docs/rules/periphery/periphery-split-csv.py
It appears that `:width: 100%` label triggers some erratic behaviour from Sphinx: column overlaps and mid-word wrapping.
After removing it, columns adapt required ratio ` :widths: 10 75 5 10`  to field content.
Applied to generation script and resulting rst.
Fixes https://github.com/SymbiFlow/sphinx_symbiflow_theme/issues/33
Tests:
Before: https://antmicro-skywater-pdk-docs.readthedocs.io/en/latest/rules/periphery.html
After:    https://antmicro-skywater-pdk-docs.readthedocs.io/en/33-periphery-rules-table-width/rules/periphery.html
=> Periphery table column width fix - removed total table width 

.github/labeler.yml
Yaml treats strings starting with a `*` character as references to previous mappings (defined with `&`). Hence any glob starting with `*` needs to be wrapped in quotes.
=> infra: Escape strings starting with *

.readthedocs.yml
=> docs: Enable cloning the sky130_fd_io submodule.

.gitmodules
This pull request adds the SkyWater foundry provided digital standard cells to the PDK.
They are being added as submodules from the https://foss-eda-tools.googlesource.com/ repository due to their large size. People are encouraged to only initialize and clone the submodules needed for their designs.
* [`sky130_fd_sc_hvl`](https://github.com/google/skywater-pdk/tree/master/libraries/sky130_fd_sc_hvl) - "High voltage" digital standard cells provided by the SkyWater foundry.
* [`sky130_fd_sc_lp`](https://github.com/google/skywater-pdk/tree/master/libraries/sky130_fd_sc_lp) - "Low power" digital standard cells provided by the SkyWater foundry.
=> Second round of adding digital standard cells

docs/index.rst
Adds links to 3 repositories with PDK design resources to the main page of the RTD. 
The links include GitHub, foss-eda-tools and Google codesearch
Fixes #159
=> Add repository links to the main page

README.rst, README.src.rst
This PR adds links to PDK repositories (including Google codesearch) to the README.rst in the. 
Resolves #159
=> Add repository links to the README.rst file

docs/rules/device-details.rst, docs/rules/device-details/cap_mim/index.rst, docs/rules/device-details/cap_var/index.rst, docs/rules/device-details/cap_vpp/index.rst, docs/rules/device-details/diodes/index.rst, docs/rules/device-details/esd_nfet/index.rst, docs/rules/device-details/nfet_01v8/index.rst, docs/rules/device-details/nfet_01v8_lvt/index.rst, docs/rules/device-details/nfet_03v3_nvt/index.rst, docs/rules/device-details/nfet_05v0_nvt/index.rst, docs/rules/device-details/nfet_20v0/index.rst, docs/rules/device-details/nfet_20v0_iso/index.rst, docs/rules/device-details/nfet_20v0_nvt/index.rst, docs/rules/device-details/nfet_20v0_zvt/index.rst, docs/rules/device-details/nfet_g11v0d16v0/index.rst, docs/rules/device-details/nfet_g5v0d10v5/index.rst, docs/rules/device-details/npn_05v0/index.rst, docs/rules/device-details/npn_05v0/npn_05v0-table0.rst, docs/rules/device-details/pfet_01v8/index.rst, docs/rules/device-details/pfet_01v8_hvt/index.rst, docs/rules/device-details/pfet_01v8_lvt/index.rst, docs/rules/device-details/pfet_20v0/index.rst, docs/rules/device-details/pfet_g5v0d10v5/index.rst, docs/rules/device-details/pfet_g5v0d16v0/index.rst, docs/rules/device-details/pnp_05v0/index.rst, docs/rules/device-details/pnp_05v0/pnp_05v0-table0.rst, docs/rules/device-details/res_high/index.rst, docs/rules/device-details/res_xhigh/index.rst, docs/rules/device-details/special_sonosfet/special_sonosfet-table1.rst, docs/rules/device-details/special_sram/index.rst
I've added a script which uses regular expressions to replace rst markup with :math: 
- subscripted variables converted from :sub: to :math:`x_y`
- equations (+ / - / * / = / |) with such variables clustered to single expression 
- fractions as :math:/frac{}{}
Updated rst files included in the commit.
Fixes #137 
Test:
https://antmicro-skywater-pdk-docs.readthedocs.io/en/137-improve-equations-and-fractions/rules/device-details.html
=> Added script converting rst subscript and equations to math. 

docs/conf.py, docs/rules/layers/table-f2a-lvs-key.rst, docs/rules/layers/table-f2b-mask-key.rst, docs/rules/summary.rst
`WARNING: Footnote [#] is not referenced` is caused by cross-document footnote linking.
Unfortunately, this is not supported by Sphinx/RST 
https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#footnotes
One solution is to use citations, which are global. 
This has two drawbacks: references cannot be numeric, and the html theme opens a new page after clicking the ref.
Another solution is to simply avoid cross-linking by including the footnotes in parent.
This PR implements second solution.
Fixes #161
=> Fix footnote warnings - table footnotes included in parent documents

scripts/python-skywater-pdk/skywater_pdk/liberty.py
This also fixes a bug in liberty_float for numbers with a magnitude between 9 and 15.
```python
Previously:
>>> liberty_float(1e15)
'1000000000000000'
>>> liberty_float(1e10)
'10000000000.'
>>> liberty_float(1e9)
'1000000000.0'
>>> liberty_float(1e16)
'1.000000e+16'
Now:
>>> liberty_float(1e15)
'1000000e+15'
>>> liberty_float(1e10)
'1000000e+10'
>>> liberty_float(1e9)
'100000000.0'
>>> liberty_float(1e16)
'1000000e+16'
```
=> Faster version of liberty_float - gives a 25% to 50% speedup

.gitmodules
=> Convert submodule sources to be github versions.

docs/environment.yml, environment.yml
A regression in PIP causes make env to fail with:
`AttributeError: 'FileNotFoundError' object has no attribute 'read'`
Incidentally, file://requirements.txt does not work:
`ValueError: non-local file URIs are not supported on this platform: 'file://requirements.txt'`
Fixes #332
> It's a good idea to open an issue first for discussion.
=> Work Around pypa/pip#10237

docs/contents/libraries.rst
It was decided that sp is too close to single port, and should be renamed bd to reference the build space.
Fixes #338 
> It's a good idea to open an issue first for discussion.
- [ x ] Tests pass
- [ x ] Appropriate changes to README are included in PR
=> Update documentation on build space from sp to bd

docs/environment.yml
Building the docs is failing because package `yosys` is missing. However, it seems not to be used/required. This PR removes it from the environment file.
=> docs/environment: do not require yosys

docs/conf.py, docs/index.rst, docs/references.rst, docs/refs.bib, docs/requirements.txt
This PR is based on #366.
Add a BibTeX file (`refs.bib`) and use it in the documentation through extension `sphinxcontrib-bibtex`.
=> docs: add References through BibTeX

.readthedocs.yml, docs/conf.py
Now it is possible to generate a nice PDF instead of HTML by ```sphinx-build -M latexpdf docs pdf```.
Also activated generation via readthedocs.io: https://docs.readthedocs.io/en/stable/config-file/v1.html#formats
Thanks,
~Cristian.
=> Enable additional PDF output for readthedocs.io

docs/rules/device-details.py, docs/rules/device-details.rst, docs/rules/device-details/cap_mim/index.rst, docs/rules/device-details/cap_var/index.rst, docs/rules/device-details/esd_nfet/index.rst, docs/rules/device-details/nfet_20v0_zvt/index.rst, docs/rules/device-details/npn_05v0/index.rst, docs/rules/device-details/pnp_05v0/index.rst, docs/rules/device-details/res_generic/index.rst
From a designer's point of view, I found the order in which devices are listed in the "Design Rules" -> "Device Details" section extremely confusing.
With this MR I propose to re-order them in a more intiuitive way: Starting with the core (1.8 V) MOS devices, followed by high voltage/ESD variants, then bipolars, special cells and finally passives. I also found it more appropriate to list the MOS varactors close to the core active devices, this is where they are typically listed in PDK documentation in my experience.
=> Reorder "Device Details" Sections
