README.rst
README.src.rst

Fix link to the skywater-pdk-users group.

---

docs/_static/metal_stack.svg

Signed-off-by: Tim Edwards <tim@efabless.com>

Adding SVG image of the metal_stack.

---

docs/_static/extra.css
docs/conf.py
docs/index.rst

* Cleanup names in the autogenerated [`docs/conf.py` file](https://github.com/google/skywater-pdk/compare/master...mithro:master#diff-85987f48f1258d9ee486e3191495582d).
* Add the image from the README to the ReadTheDocs output.

Minor documentation updates

---

docs/conf.py

docs: Fix the header links.

---

README.rst
README.src.rst

docs: Fix the build badge for ReadTheDocs.

---

.github/labels.yml

infra: Adding Synopsys DesignCompiler label.

---

.github/autolabeler.yml
.github/labels.yml

* libraries/sky130_fd_sc_hd/latest c0d4f99...7f79525 (1):
> Adding complete technology LEF file.
* libraries/sky130_fd_sc_hd/v0.0.1 7fb23b9...4cbecdc (1):
> Adding complete technology LEF file.
* libraries/sky130_fd_sc_hd/v0.0.2 c0d4f99...7f79525 (1):
> Adding complete technology LEF file.
* libraries/sky130_fd_sc_hdll/latest dfb3a88...c4512ed (1):
> Adding complete technology LEF file.
* libraries/sky130_fd_sc_hdll/v0.1.0 2d15473...60697a7 (1):
> Adding complete technology LEF file.
* libraries/sky130_fd_sc_hdll/v0.1.1 dfb3a88...c4512ed (1):
> Adding complete technology LEF file.
* libraries/sky130_fd_sc_hs/latest fb0e900...8bc807e (1):
> Adding complete technology LEF file.
* libraries/sky130_fd_sc_hs/v0.0.1 10be0bc...73908d9 (1):
> Adding complete technology LEF file.
* …

Adding complete technology LEF files for digital standard cells

---

.github/autolabeler.yml
.github/labels.yml

* Adding the labels 
* Auto-labelling pull requests

infra: Labels related to specific scripts.

---

README.rst
README.src.rst

Fix types in README.rst file

---

docs/rules/assumptions.rst
docs/rules/gds_layers.csv
docs/rules/gds_layers.rst

This is from https://docs.google.com/spreadsheets/d/176OcP2h_TT_pDP2-zBLijlgFUP38LVgMQPlDtpLcrsk/edit?ts=5eff8387#gid=459375686
Signed-off-by: Sylvain Munaut <tnt@246tNt.com>

docs: Add CSV file with the GDS layer informations and comments

---

scripts/python-skywater-pdk/skywater_pdk/liberty.py

Fix ccsnoise properties ending up in basic liberty files.

---

.github/autolabeler.yml
.github/labels.yml
scripts/python-skywater-pdk/skywater_pdk/liberty.py

* Adding label for build files.
* Adding `--debug` to the liberty file generator.

Two small fixes

---

scripts/python-skywater-pdk/skywater_pdk/liberty.py

scripts/liberty: Second attempt at filtering all ccsnoise data.

---

.github/labels.yml

infra: Adding in-progress label.

---

scripts/python-skywater-pdk/skywater_pdk/liberty.py

Fix power pins

---

README.rst
README.src.rst
scripts/make/git.mk

Fixes #108 by adding a make target.

Add 'make submodules' to download standard cell libraries

---

docs/glossary.rst

Alphabetize the acronyms section.
Fix the link to Mentor Graphics.
> It's a good idea to open an issue first for discussion.
N/A - Discussed in Slack

glossary: Add suggestions from Slack

---

README.rst
README.src.rst

Did not create an issue, because the change is trivial.
This change fixes the code block in the readme to be in RST format instead of markdown

Fix the code block in the README

---

docs/rules/layers.rst
docs/rules/layers/table-c4b-layer-description.csv
docs/rules/rcx.rst
docs/rules/rcx/capacitance-fringe-downward.tsv
docs/rules/rcx/capacitance-fringe-upward.tsv
docs/rules/rcx/capacitance-parallel.tsv
docs/rules/rcx/capacitance-rules.csv
docs/rules/rcx/resistance-rules.csv
docs/rules/rcx/resistance-values.tsv

Values taken from the following Google Spreadsheet
[SkyWater Layer (GDS-II / Magic / Calibre / etc) Information - Layer resistances and capacitances](https://docs.google.com/spreadsheets/d/176OcP2h_TT_pDP2-zBLijlgFUP38LVgMQPlDtpLcrsk/edit?ts=5eff8387#gid=1059412464)

docs: Adding basic values for capacitance + resistance.

---

docs/contents/libraries.rst
docs/contents/libraries/foundry-provided.rst

docs: Adding summary of foundry provided cells.

---

scripts/python-skywater-pdk/skywater_pdk/liberty.py

Adds the output flags -o and --output_directory to control the output of the liberty files.

scripts/liberty: Adds output directory customization

---

docs/conf.py

Added Apache 2.0 license link using Symbiflow theme 
Fixes #118

Added license link in the footer

---

docs/Makefile

Enable not using conda for docs build

---

.github/workflows/dependabot-gha.yml

infra: Use dependabot to automatically update GitHub actions.

---

.github/kokoro/continuous.cfg
.github/kokoro/presubmit.cfg
.github/kokoro/run.sh
.github/kokoro/steps/auth.sh
.github/kokoro/steps/git.sh
.github/kokoro/steps/hostinfo.sh
.github/kokoro/steps/hostsetup.sh

infra: Adding kokoro setup.

---

.github/labeler.yml

infra: Add a little bit of documentation to labeler.yml file.

---

docs/previous.rst

Removed duplicated keys from previous.rst

---

.gitmodules

Update submodules branch name to main.

---

Makefile
scripts/make/git.mk

Fix the cloning of library submodules

---

docs/rules/device-details/nfet_05v0_nvt/index.rst

docs: Fix nfet_05v0_nvt cell name.

---

.gitmodules

This pull request adds ReRAM to the Skywater PDK. ReRAM is implemented a MiM type device between metal1 and metal2 in the layer stack up. These device with special programming allow you to store up to two bits of information per device; taking up the same amount of space as a metal1 to metal2 via. 
Signed-off-by: Ethan Mahintorabi <ethanmoon@google.com>
Fixes google/skywater-pdk-libs-sky130_fd_pr_reram#7 
- [ x ] Tests pass
- [ x ] Appropriate changes to README are included in PR

Adding ReRAM PDK to the submodules directory of the skywater repo

---

.github/labels.yml

github/labels: add ngspice

---

docs/conf.py

Fixing Sphinx config for GitHub.

---

docs/_templates/relbar.html

Fixing the announcement link in top level bar.

---

.github/labels.yml

Adding a blocker label.

---

environment.yml
requirements.txt
scripts/python-skywater-pdk/skywater_pdk/cells/generate/vcd2wavedrom.py
scripts/python-skywater-pdk/skywater_pdk/cells/generate/waveform.py

This PR adds a script computing cell's Verilog testbed `*.tb.v` into VCD waveform.
The cell is simulated using Icarus Verilog.
The script produces 2 vcd files: one for logic pins only and one including power pins toggling. 
Subsequent work involves VCD -> wavedrom -> SVG conversion 
Addresses #87

Cell VCD waveform generator script
